apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-tracker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - thapham1404.eastus2.cloudapp.azure.com
    secretName: aks-ingress-tls
  rules:
  - host: thapham1404.eastus2.cloudapp.azure.com
    http:
      paths:
      - path: /ui
        backend:
          serviceName: service-tracker-ui
          servicePort: 8080